### ISSUE TITLE
Update Example to Phoenix v1.4

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-ecto-append-only-log-example#14]
The example is using Phoenix 1.3 at the moment:
https://github.com/dwyl/phoenix-ecto-append-only-log-example/blob/e8eee00fab8f1555ab93c2d2757c497207d81873/mix.exs#L39

We can update the Phoenix version to 1.4 and make sure all the steps are still working.

see https://github.com/dwyl/learn-phoenix-framework/issues/118#issue-378671819

**Comment by SimonLab** [comment]
Phoenix 1.4 is using Ecto v3.0 and the following test is failing:
https://github.com/dwyl/phoenix-ecto-append-only-log-example/blob/e8eee00fab8f1555ab93c2d2757c497207d81873/test/append/address_test.exs#L35-L41

This is due to the new way Ecto is dealing with the precision of the timestamps (see http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/):
![image](https://user-images.githubusercontent.com/6057298/48812181-08b01680-ed29-11e8-8d1f-52d4624e197a.png)

This means that when the `get` function is called, the `order_by` clause might not return the correct result because the test insert almost at the same time the item and the updated version:
https://github.com/dwyl/phoenix-ecto-append-only-log-example/blob/e8eee00fab8f1555ab93c2d2757c497207d81873/lib/append/append_only_log.ex#L35-L48 

I can see two solutions to fix this:
- [ ] use the new type `naive_datetime_usec` as describe in the breaking change page and keep the microseconds in the `inserted_at` property
- [ ] delay the update in the test (at least 1s) by using Process.sleep(1000)

**Comment by nelsonic** [comment]
@SimonLab _thank you_ for summarising the Ecto 3.0 changes so others can learn from your research! 😍 

While I _understand_ the reasoning behind the _breaking_ change in Ecto to force people to no longer rely on having high-precision time in the database (_let's face it: most people don't need microseconds!_) I _disagree_ with removing them as it's "_dumbing down_" elixir to make it more like Ruby or JS. 😞 

High precision time is one of Erlang's (_and thus Elixir's_) best features when it comes to low-latency and we _want_ to have it in our projects so that we can _measure_ latency and database insert volume at a more granular level.

My preference is to use the **`naive_datetime_usec`** type so we capture the more detailed time info.

If it turns out later that we don't _need_ microseconds in our apps, we can always refactor and adopt the `Process.sleep(1000)` approach (_which feels "dirty" to me_).

**Comment by SimonLab** [comment]
Readme and code updated with #15
